import { getDb } from "../api/queries/connection.js";
import { posts } from "./schema.js";

async function seed() {
  const db = getDb();

  // Check if data already exists
  const existing = await db.select().from(posts).limit(1);
  if (existing.length > 0) {
    console.log("Database already seeded.");
    return;
  }

  const seedPosts = [
    {
      title: "PhD Position in Multimodal LLM Reasoning",
      type: "position" as const,
      positionType: "PhD Student" as const,
      source: "X" as const,
      institution: "Stanford University",
      location: "Stanford, CA",
      authorName: "Dr. Sarah Chen",
      authorAffiliation: "Stanford University",
      summary: "Looking for motivated PhD students interested in multimodal reasoning, vision-language models, and embodied AI. Full funding guaranteed for 5 years.",
      originalText: "We are recruiting PhD students for Fall 2026! Our lab focuses on multimodal LLM reasoning and embodied intelligence. Full funding + summer internship support. Looking for students with strong programming skills and research passion. Please DM me your CV and a brief research statement.",
      tags: "NLP,Computer Vision,Multimodal",
      originalUrl: "https://x.com/example",
      status: "Open for Applications" as const,
      deadline: "2026-12-15",
    },
    {
      title: "Research Internship — Diffusion Models for Scientific Computing",
      type: "position" as const,
      positionType: "Research Intern" as const,
      source: "LinkedIn" as const,
      institution: "MIT CSAIL",
      location: "Cambridge, MA",
      authorName: "Prof. Michael Zhang",
      authorAffiliation: "MIT CSAIL",
      summary: "Summer 2026 research internship available. Work on applying diffusion models to PDE solving and molecular simulation. Strong PyTorch background preferred.",
      originalText: "We have an opening for a summer research intern in our group at MIT CSAIL. The project focuses on using diffusion models for scientific computing applications, specifically PDE solving and molecular dynamics simulation. Requirements: strong PyTorch skills, background in ML and numerical methods. Duration: 3 months.",
      tags: "Diffusion Models,Scientific Computing,Deep Learning",
      originalUrl: "https://linkedin.com/example",
      status: "Open for Applications" as const,
      deadline: "2026-05-01",
    },
    {
      title: "PhD Students — Robotics and Embodied AI",
      type: "position" as const,
      positionType: "PhD Student" as const,
      source: "RedBook" as const,
      institution: "清华大学",
      location: "北京",
      authorName: "李教授",
      authorAffiliation: "清华大学智能产业研究院",
      summary: "招收2026年秋季入学博士生，研究方向为机器人学习与具身智能。提供全额奖学金及海外交流机会。",
      originalText: "我们实验室正在招收2026年秋季入学的博士研究生！研究方向：机器人学习、具身智能、强化学习。我们提供全额奖学金资助，以及丰富的海外学术交流机会。欢迎私信联系，请附上简历和研究兴趣说明。",
      tags: "Robotics,Embodied AI,Reinforcement Learning",
      originalUrl: "https://xiaohongshu.com/example",
      status: "Open for Applications" as const,
    },
    {
      title: "PostDoc in Trustworthy Machine Learning",
      type: "position" as const,
      positionType: "PostDoc" as const,
      source: "LinkedIn" as const,
      institution: "ETH Zurich",
      location: "Zurich, Switzerland",
      authorName: "Prof. Anna Mueller",
      authorAffiliation: "ETH Zurich",
      summary: "Two-year postdoctoral position available immediately. Research on adversarial robustness, fairness, and explainability in ML systems.",
      originalText: "We are seeking a postdoctoral researcher to join our Trustworthy ML group at ETH Zurich. The position is for 2 years with possible extension. Research areas: adversarial robustness, algorithmic fairness, explainable AI. Competitive salary and conference travel support.",
      tags: "Trustworthy ML,Adversarial Robustness,XAI",
      originalUrl: "https://linkedin.com/example2",
      status: "Reviewing Applications" as const,
    },
    {
      title: "Research Assistant — Natural Language Processing",
      type: "position" as const,
      positionType: "Research Assistant" as const,
      source: "X" as const,
      institution: "University of Edinburgh",
      location: "Edinburgh, UK",
      authorName: "Dr. James Wilson",
      authorAffiliation: "University of Edinburgh",
      summary: "6-month RA position for recent graduates. Work on low-resource language modeling and multilingual NLP.",
      originalText: "Hiring a Research Assistant for a 6-month project on low-resource language modeling! The role is perfect for recent graduates looking to gain research experience before applying for PhD programs.",
      tags: "NLP,Low-resource Languages,Multilingual",
      originalUrl: "https://x.com/example2",
      status: "Open for Applications" as const,
      deadline: "2026-06-30",
    },
    {
      title: "PhD Position — AI for Healthcare & Drug Discovery",
      type: "position" as const,
      positionType: "PhD Student" as const,
      source: "LinkedIn" as const,
      institution: "Carnegie Mellon University",
      location: "Pittsburgh, PA",
      authorName: "Prof. Lisa Park",
      authorAffiliation: "CMU Machine Learning Department",
      summary: "Fully-funded PhD position at CMU MLD. Research at the intersection of graph neural networks and drug discovery.",
      originalText: "Our group at CMU MLD is recruiting PhD students for Fall 2026! We work on applying graph neural networks and geometric deep learning to drug discovery and molecular property prediction. Full funding guaranteed.",
      tags: "GNN,Drug Discovery,Healthcare AI",
      originalUrl: "https://linkedin.com/example3",
      status: "Open for Applications" as const,
    },
    {
      title: "Summer Research Intern — Computer Vision",
      type: "position" as const,
      positionType: "Research Intern" as const,
      source: "RedBook" as const,
      institution: "上海人工智能实验室",
      location: "上海",
      authorName: "王研究员",
      authorAffiliation: "上海AI实验室",
      summary: "招收暑期实习生，研究方向为三维视觉与神经辐射场。实习期3-6个月，优秀者可转正。",
      originalText: "上海AI实验室三维视觉组招收暑期实习生！研究方向：NeRF/3D Gaussian Splatting、三维重建、新视角合成。实习期3-6个月，提供有竞争力的实习补贴。",
      tags: "3D Vision,NeRF,Computer Vision",
      originalUrl: "https://xiaohongshu.com/example2",
      status: "Open for Applications" as const,
    },
    {
      title: "PostDoc — Reinforcement Learning Theory",
      type: "position" as const,
      positionType: "PostDoc" as const,
      source: "X" as const,
      institution: "UC Berkeley",
      location: "Berkeley, CA",
      authorName: "Prof. Robert Taylor",
      authorAffiliation: "UC Berkeley",
      summary: "Postdoc opening in RL theory group. Focus on sample-efficient RL, offline RL theory, and representation learning.",
      originalText: "We are looking for a postdoc to join our RL theory group at UC Berkeley EECS. The research will focus on theoretical foundations of reinforcement learning.",
      tags: "RL Theory,Offline RL,Representation Learning",
      originalUrl: "https://x.com/example3",
      status: "Open for Applications" as const,
    },
    {
      title: "Research Internship — LLM Safety & Alignment",
      type: "position" as const,
      positionType: "Research Intern" as const,
      source: "LinkedIn" as const,
      institution: "Anthropic",
      location: "San Francisco, CA",
      authorName: "Dr. Emily Brown",
      authorAffiliation: "Anthropic",
      summary: "Research intern position for summer 2026. Work on constitutional AI, red teaming, and scalable oversight.",
      originalText: "Anthropic is hiring research interns for Summer 2026! Join our safety team to work on constitutional AI, automated red teaming, and scalable oversight mechanisms.",
      tags: "LLM Safety,AI Alignment,Red Teaming",
      originalUrl: "https://linkedin.com/example4",
      status: "Reviewing Applications" as const,
    },
    {
      title: "PhD Students — Neuro-Symbolic AI",
      type: "position" as const,
      positionType: "PhD Student" as const,
      source: "X" as const,
      institution: "UCLA",
      location: "Los Angeles, CA",
      authorName: "Prof. David Kumar",
      authorAffiliation: "UCLA",
      summary: "Multiple PhD positions available. Research on combining neural networks with symbolic reasoning for scientific discovery.",
      originalText: "Multiple PhD positions available in our Neuro-Symbolic AI lab at UCLA! We combine deep learning with symbolic reasoning and program synthesis.",
      tags: "Neuro-symbolic AI,Reasoning,Scientific Discovery",
      originalUrl: "https://x.com/example4",
      status: "Open for Applications" as const,
    },
    {
      title: "Research Assistant — AI for Climate Science",
      type: "position" as const,
      positionType: "Research Assistant" as const,
      source: "RedBook" as const,
      institution: "浙江大学",
      location: "杭州",
      authorName: "陈博士",
      authorAffiliation: "浙江大学",
      summary: "招收研究助理，参与AI for Earth项目。利用深度学习进行气候预测和极端天气事件检测。",
      originalText: "浙江大学地球科学学院招收研究助理！参与AI for Earth项目，利用深度学习进行气候预测、极端天气事件检测和碳排放估算。",
      tags: "Climate AI,Time Series,Earth Science",
      originalUrl: "https://xiaohongshu.com/example3",
      status: "Open for Applications" as const,
    },
    {
      title: "PostDoc — Speech and Audio Generation",
      type: "position" as const,
      positionType: "PostDoc" as const,
      source: "LinkedIn" as const,
      institution: "Google Research",
      location: "London, UK",
      authorName: "Prof. Maria Garcia",
      authorAffiliation: "Google Research",
      summary: "Postdoc position in speech synthesis and audio generation team. Work on zero-shot TTS and music generation.",
      originalText: "Google Research London is looking for a postdoctoral researcher in our Speech and Audio team. Research focus: zero-shot text-to-speech, neural audio codec, and controllable music generation.",
      tags: "Speech Synthesis,Audio Generation,Music AI",
      originalUrl: "https://linkedin.com/example5",
      status: "Open for Applications" as const,
    },
    // Collaborators
    {
      title: "Looking for co-author on Diffusion Model for Medical Imaging",
      type: "collaborator" as const,
      domain: "Co-author Needed" as const,
      source: "X" as const,
      institution: "MIT",
      location: null,
      authorName: "Alex Johnson",
      authorAffiliation: "Researcher at MIT",
      summary: "We have a strong paper draft on using diffusion models for 3D medical image reconstruction. Looking for a co-author with clinical imaging experience.",
      originalText: "Seeking a co-author for our medical imaging paper! We have developed a novel diffusion-based approach for 3D medical image reconstruction with strong quantitative results. The draft is nearly complete but we need someone with clinical radiology/imaging background.",
      tags: "Computer Vision,Medical Imaging,Diffusion Models",
      originalUrl: "https://x.com/example5",
      status: "Manuscript Draft Ready" as const,
      projectStatus: "Manuscript Draft Ready",
    },
    {
      title: "Long-term collaborator for embodied AI benchmark project",
      type: "collaborator" as const,
      domain: "Long-term Research" as const,
      source: "LinkedIn" as const,
      institution: "DeepMind",
      location: null,
      authorName: "Dr. Wei Liu",
      authorAffiliation: "Research Scientist at DeepMind",
      summary: "Building a large-scale benchmark for embodied agents in household environments. Looking for researchers interested in long-term collaboration.",
      originalText: "I am initiating a long-term project to build a comprehensive benchmark for evaluating embodied AI agents in realistic household environments.",
      tags: "Embodied AI,Benchmarks,Robotics",
      originalUrl: "https://linkedin.com/example6",
      status: "Early Stage" as const,
      projectStatus: "Early Stage",
    },
    {
      title: "寻找RL方向短期项目合作者",
      type: "collaborator" as const,
      domain: "Short-term Project" as const,
      source: "RedBook" as const,
      institution: "南京大学",
      location: null,
      authorName: "小张研究员",
      authorAffiliation: "南京大学LAMDA组",
      summary: "有一个2-3个月的短期项目，关于多智能体强化学习中的信用分配问题。寻找1-2位有MARL经验的同学合作。",
      originalText: "我们有一个关于多智能体强化学习中信用分配问题的短期研究想法，预计周期2-3个月。目标是在一个顶级会议上发表一篇短文。",
      tags: "MARL,Credit Assignment,Game Theory",
      originalUrl: "https://xiaohongshu.com/example4",
      status: "Idea Stage" as const,
      projectStatus: "Idea Stage",
    },
    {
      title: "Need co-author for survey on LLM reasoning",
      type: "collaborator" as const,
      domain: "Co-author Needed" as const,
      source: "X" as const,
      institution: "Mila",
      location: null,
      authorName: "Dr. Rachel Green",
      authorAffiliation: "Postdoc at Mila",
      summary: "Survey paper on chain-of-thought reasoning and tool-use in LLMs. Outline is ready. Need co-authors with expertise in either formal methods or tool learning.",
      originalText: "I am working on a comprehensive survey paper on reasoning capabilities in large language models, covering chain-of-thought prompting, self-consistency, tool-augmented reasoning, and formal verification.",
      tags: "LLM Reasoning,Chain-of-Thought,Tool Learning",
      originalUrl: "https://x.com/example6",
      status: "Outline Ready" as const,
      projectStatus: "Outline Ready",
    },
    {
      title: "Collaboration on federated learning privacy",
      type: "collaborator" as const,
      domain: "Long-term Research" as const,
      source: "LinkedIn" as const,
      institution: "University of Tokyo",
      location: null,
      authorName: "Prof. Kenji Tanaka",
      authorAffiliation: "University of Tokyo",
      summary: "Seeking collaborators for a long-term research project on differential privacy in federated learning. Funding available for visiting researchers.",
      originalText: "Our lab at the University of Tokyo has secured a 3-year grant for research on privacy-preserving federated learning. We are looking for 1-2 international collaborators who can visit for 3-6 months.",
      tags: "Federated Learning,Differential Privacy,Security",
      originalUrl: "https://linkedin.com/example7",
      status: "Grant Funded" as const,
      projectStatus: "Grant Funded",
    },
    {
      title: "短期项目：多模态文档理解",
      type: "collaborator" as const,
      domain: "Short-term Project" as const,
      source: "RedBook" as const,
      institution: "阿里巴巴",
      location: null,
      authorName: "李工程师",
      authorAffiliation: "阿里巴巴达摩院",
      summary: "有一个3个月的工业界合作项目，关于多模态文档理解（版面分析+OCR+语义理解）。寻找学术界合作者。",
      originalText: "达摩院正在开展一个多模态文档理解的短期研究项目，目标是提升复杂版面的理解能力。周期3个月，有充足的计算资源和标注数据。",
      tags: "Document AI,OCR,Multimodal",
      originalUrl: "https://xiaohongshu.com/example5",
      status: "Industry Partnership" as const,
      projectStatus: "Industry Partnership",
    },
  ];

  for (const post of seedPosts) {
    await db.insert(posts).values(post);
  }

  console.log(`Seeded ${seedPosts.length} posts.`);
}

seed().catch(console.error);
